// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"coderrob.com/meraki-cmx-receiver/pkg/http"
	"coderrob.com/meraki-cmx-receiver/pkg/http/controllers"
	"coderrob.com/meraki-cmx-receiver/pkg/services"
	"github.com/google/wire"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func InitializeFeedController(config map[string]services.Settings) (*controllers.FeedController, error) {
	iOrganizationService := services.NewOrganizationService(config)
	iLocationService := services.NewLocationService()
	feedController := controllers.NewFeedController(iOrganizationService, iLocationService)
	return feedController, nil
}

func InitializeServer(router *mux.Router) (*http.Server, error) {
	server := http.NewServer(router)
	return server, nil
}

// wire.go:

// ServiceSet is the set of common services used by controllers
var ServiceSet = wire.NewSet(services.NewOrganizationService, services.NewLocationService)
